version: '3.3'
services:
  us-core-vmc:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    container_name: us-core-vmc-container